name: Deploy to AWS with Terraform

on:
  push:
    branches:
      - main
permissions:
    contents: write
    id-token: write
jobs:
  deploy-iac:
    runs-on: terraform
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v2

      - name: Setup GitHub OIDC
        run: | 
           curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
           unzip awscliv2.zip
           sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update


      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            # Removed role-to-assume as requested
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
            cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}



      - name: 'Install tfsec for security scanning'
        run: |
          curl -sLo tfsec https://github.com/aquasecurity/tfsec/releases/download/v1.28.11/tfsec-linux-amd64
          chmod +x tfsec
          ./tfsec --version

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Format'
        run: terraform fmt

      - name: 'Terraform Validate'
        run: terraform validate


      - name: 'tfsec Security Scan.'
        run: ./tfsec . || true

      - name: Terraform Plan
        run: terraform plan 

      # - name: Terraform Apply.
      #   run: terraform apply -auto-approve 

      # - name: 'install kubectl'
      #   run: |
      #     curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      #     chmod +x ./kubectl
      #     sudo mv ./kubectl /usr/local/bin/kubectl

      # - name: 'authenticate to EKS Cluster'
      #   run: aws eks update-kubeconfig --name ${{ vars.EKS_CLUSTER_NAME }} --region us-east-1
      
      # - name: 'Deploying the ClusterIssuer to EKS'
      #   run: kubectl apply -f ClusterIssuer.yaml

      # - name: 'Deploying argocd ingress rule to EKS'
      #   run: kubectl apply -f ingress-argocd.yaml -n argocd

      - name: Terraform Destroy
        run: terraform destroy -auto-approve 
